### PR TITLE
Create ringer.go and package ringer

### PR DESCRIPTION
**Pull request by gfr10598**
This change is [Reviewable](https://reviewable.io/reviews/kirbyer/ringer-sim/1)

### CODE REVIEW

**Comment by KirbyER** [comment]
Ringer-package should be in a subdirectory called "ringer".

**Comment by gfr10598** [comment]
Done.

**Comment by KirbyER** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[ringer/ringer.go, line 1 at r2](https://reviewable.io:443/reviews/kirbyer/ringer-sim/1#-L05GYy1S3aLRkiLEB9L:-L05GYy1S3aLRkiLEB9M:boiwmdy) ([raw file](https://github.com/kirbyer/ringer-sim/blob/f34c59ceb15e716648e6df659fc83c132900290d/ringer/ringer.go#L1)):*
> ```Go
> package ringer
> ```

This should have a comment.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kirbyer/ringer-sim/1)*

**Comment by gfr10598** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[ringer/ringer.go, line 1 at r2](https://reviewable.io:443/reviews/kirbyer/ringer-sim/1#-L05GYy1S3aLRkiLEB9L:-L05JWVttDBLT6xDaS6z:b-896fix) ([raw file](https://github.com/kirbyer/ringer-sim/blob/f34c59ceb15e716648e6df659fc83c132900290d/ringer/ringer.go#L1)):*
<details><summary><i>Previously, KirbyER wrote…</i></summary><blockquote>

This should have a comment.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kirbyer/ringer-sim/1)*

**Comment by KirbyER** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kirbyer/ringer-sim/1#-:-L05JkkSFjfKsFk2rwu_:bnfp4nl)*

**Comment by gfr10598** [comment]
Reviewed 1 of 2 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kirbyer/ringer-sim/1)*

**Pull request merged**
